import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { mkdir, writeFile, readFile, unlink } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);require('@next/env').loadEnvConfig(process.cwd());
const url=new URL(process.env.TEST_DATABASE_URL || process.env.DATABASE_URL);
if(!['localhost','127.0.0.1'].includes(url.hostname)) throw Error('Local database required');
url.pathname='/kiwi_journeys_audit_test';
const env={...process.env,DATABASE_URL:url.toString(),AUTH_SECRET:randomUUID()+randomUUID(),ENABLE_INTERNAL_CRON:'false',CONTENT_DEMO_MODE:'false'};
for(const key of ['RESEND_API_KEY','STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET','BLOB_READ_WRITE_TOKEN','TWILIO_ACCOUNT_SID','TWILIO_AUTH_TOKEN','META_WHATSAPP_TOKEN','META_WHATSAPP_PHONE_ID']) env[key]='';
const {PrismaClient}=require('@prisma/client');const db=new PrismaClient({datasources:{db:{url:url.toString()}}});
const bcrypt=require('bcryptjs');const password=randomUUID();const email=`cms-${randomUUID()}@example.invalid`;
const admin=await db.adminUser.create({data:{email,passwordHash:await bcrypt.hash(password,10),name:'CMS audit'}});
await db.siteSetting.upsert({where:{id:'singleton'},create:{name:'CMS audit',heroImage:'/images/brand/Hero-Ocean-Alps.jpg'},update:{}});
const out='outputs/audit/2026-09-25';await mkdir(out,{recursive:true});
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--port','3102'],{env,stdio:['ignore','pipe','pipe']});let serverLog='';server.stdout.on('data',b=>serverLog+=b);server.stderr.on('data',b=>serverLog+=b);
const {chromium}=createRequire(`${process.env.AUDIT_TOOLS||'/tmp/kiwi-audit-tools'}/package.json`)('playwright');
let browser;const results=[];const base='http://localhost:3102';
async function check(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:e.message});throw e;}}
try{
 for(let i=0;i<80;i++){try{if((await fetch(base+'/api/health')).ok)break;}catch{} await new Promise(r=>setTimeout(r,250));}
 browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage();page.on('dialog',dialog=>dialog.accept());
 await check('Unauthenticated admin pages and API are protected',async()=>{await page.goto(base+'/admin/settings');assert.ok(page.url().includes('/admin/login'));assert.equal((await page.request.get(base+'/api/admin/bookings')).status(),401);});
 await check('Admin login via form',async()=>{await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(base+'/admin/settings');});
 for(const path of ['','tours','tours/new','destinations','blog','testimonials','settings','media','bookings','calendar','customers','gift-vouchers','promo-codes','waitlist','users','analytics','operations']) await check('Admin page /'+path,async()=>{const r=await page.goto(base+'/admin/'+path);assert.equal(r.status(),200);assert.ok(!page.url().includes('/login'));assert.equal(await page.getByText('Application error',{exact:false}).count(),0);});
 await check('Settings rejects malformed JSON without changing stored content',async()=>{await page.goto(base+'/admin/settings');const before=await db.siteSetting.findUnique({where:{id:'singleton'}});await page.locator('[name=nav]').fill('[');await page.getByRole('button',{name:'Save settings'}).click();await page.getByRole('alert').waitFor();assert.deepEqual((await db.siteSetting.findUnique({where:{id:'singleton'}})).nav,before.nav);});
 await check('Settings saves valid structured content',async()=>{await page.goto(base+'/admin/settings');await page.locator('[name=tagline]').fill('Same-day CMS audit');await page.getByRole('button',{name:'Save settings'}).click();await page.waitForTimeout(500);assert.equal((await db.siteSetting.findUnique({where:{id:'singleton'}})).tagline,'Same-day CMS audit');});
 const slug='cms-audit-'+Date.now();
 await check('Create day tour with prices through CMS',async()=>{await page.goto(base+'/admin/tours/new');for(const[k,v]of Object.entries({title:'CMS audit day trip',slug,destination:'Test',durationMins:'480',durationLabel:'1 Day',summary:'A same-day audit trip',priceOptions:'adult | Adult | 125 | 1',departureTimes:'08:30',departureWeekdays:'1,2,3,4,5,6,7'}))await page.locator(`[name="${k}"]`).fill(v);await page.getByRole('button',{name:'Save tour',exact:true}).click();await page.waitForURL(base+'/admin/tours');const t=await db.tour.findUnique({where:{slug},include:{priceOptions:true}});assert.equal(t.priceOptions[0].priceCents,12500);});
 const tour=await db.tour.findUniqueOrThrow({where:{slug}});
 await check('Invalid tour price gives a visible error without changing saved tour',async()=>{await page.goto(base+'/admin/tours/'+tour.id);await page.locator('[name=title]').fill('Must not persist');await page.locator('[name=priceOptions]').fill('adult | Adult | -10 | 1');await page.getByRole('button',{name:'Save tour',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal((await db.tour.findUnique({where:{id:tour.id}})).title,'CMS audit day trip');});
 await check('Booked price removal rolls back the entire tour edit',async()=>{const option=await db.priceOption.findFirstOrThrow({where:{tourId:tour.id}});const session=await db.session.create({data:{tourId:tour.id,startsAtUtc:new Date('2028-01-01T00:00:00Z'),localDate:new Date('2028-01-01'),capacity:12}});const customer=await db.customer.create({data:{email:'cms-booking-'+Date.now()+'@example.invalid',fullName:'CMS audit'}});const booking=await db.booking.create({data:{reference:'CMS-'+Date.now(),stripePaymentIntentId:'pi_cms_'+Date.now(),sessionId:session.id,customerId:customer.id,seats:1,totalCents:12500,items:{create:{priceOptionId:option.id,label:'Adult',unitPriceCents:12500,qty:1,seats:1}}}});try{await page.goto(base+'/admin/tours/'+tour.id);await page.locator('[name=title]').fill('Must also not persist');await page.locator('[name=priceOptions]').fill('new | New option | 100 | 1');await page.getByRole('button',{name:'Save tour',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal((await db.tour.findUnique({where:{id:tour.id}})).title,'CMS audit day trip');assert.equal(await db.priceOption.count({where:{id:option.id}}),1);}finally{await db.booking.delete({where:{id:booking.id}});await db.session.delete({where:{id:session.id}});await db.customer.delete({where:{id:customer.id}});}});
 await check('Authenticated booking CSV export responds with CSV',async()=>{const r=await page.request.get(base+'/api/admin/bookings/export');assert.equal(r.status(),200);assert.match(r.headers()['content-type'],/text\/csv/);assert.match(await r.text(),/Reference/);});
 await check('Published tour visible; editing and unpublishing removes public page',async()=>{assert.equal((await page.request.get(base+'/tours/'+slug)).status(),200);await page.goto(base+'/admin/tours/'+tour.id);await page.locator('[name=title]').fill('Updated CMS day trip');await page.locator('[name=isActive]').uncheck();await page.getByRole('button',{name:'Save tour',exact:true}).click();await page.waitForURL(base+'/admin/tours');assert.equal((await db.tour.findUnique({where:{id:tour.id}})).title,'Updated CMS day trip');await page.goto(base+'/tours/'+slug); await page.getByRole('heading',{name:'Off the map'}).waitFor(); assert.equal(await page.getByRole('heading',{name:'Updated CMS day trip',exact:true}).count(),0);});
 for(const spec of [{path:'destinations',model:'destination',key:'name',value:'CMS audit destination',data:{name:'CMS audit destination',slug:'cms-destination-'+Date.now(),blurb:'Day trips'}},{path:'blog',model:'blogPost',key:'title',value:'CMS audit article',data:{title:'CMS audit article',slug:'cms-article-'+Date.now(),body:'An audit paragraph.',excerpt:'Audit'}},{path:'testimonials',model:'testimonial',key:'name',value:'CMS audit guest',data:{name:'CMS audit guest',text:'Test fixture, not a real review.'}}]){
 await check(spec.path+' create/edit/delete through CMS',async()=>{await page.goto(base+'/admin/'+spec.path);const form=page.locator('form').filter({has:page.locator(`[name=${spec.key}]`)}).first();for(const[k,v]of Object.entries(spec.data))await form.locator(`[name=${k}]`).fill(v);await form.getByRole('button',{name:'Save',exact:true}).click();await page.waitForTimeout(500);let row=await db[spec.model].findFirstOrThrow({where:{[spec.key]:spec.value}});await page.reload();const details=page.locator('details').filter({hasText:spec.value});await details.locator('summary').click();await details.locator(`[name=${spec.key}]`).fill(spec.value+' edited');await details.getByRole('button',{name:'Save',exact:true}).click();await page.waitForTimeout(500);assert.equal((await db[spec.model].findUnique({where:{id:row.id}}))[spec.key],spec.value+' edited');await page.reload();const edited=page.locator('details').filter({hasText:spec.value+' edited'});await edited.locator('summary').click();await edited.getByRole('button',{name:'Delete',exact:true}).click();await page.waitForTimeout(500);assert.equal(await db[spec.model].count({where:{id:row.id}}),0);});
 }
 await check('Upload rejects non-images',async()=>{const r=await page.request.post(base+'/api/admin/upload',{multipart:{file:{name:'audit.html',mimeType:'text/html',buffer:Buffer.from('<h1>test</h1>')}}});assert.equal(r.status(),415);});
 await check('Media library renders a stored image and exposes its URL',async()=>{const media=await db.media.create({data:{url:'/images/brand/Hero-Ocean-Alps.jpg',alt:'Audit image'}});try{await page.goto(base+'/admin/media');await page.getByRole('heading',{name:'Media Library'}).waitFor();const input=page.getByRole('textbox',{name:'Image URL'}).first();await input.focus();assert.ok(await input.inputValue());}finally{await db.media.delete({where:{id:media.id}});}});
 await check('New uploaded image is immediately accessible',async()=>{const r=await page.request.post(base+'/api/admin/upload',{multipart:{file:{name:'cms-audit.webp',mimeType:'image/webp',buffer:await readFile('public/images/brand/carriage-interior.webp')}}});assert.equal(r.status(),200);const {url}=await r.json();try{assert.equal((await page.request.get(base+url)).status(),200);}finally{await db.media.deleteMany({where:{url}});await unlink(process.env.UPLOAD_DIR?process.env.UPLOAD_DIR+url.slice('/uploads'.length):'public'+url);}});
 await check('Create and cancel one-off departure',async()=>{await page.goto(base+'/admin/tours/'+tour.id);const form=page.locator('form').filter({has:page.locator('[name=date]')});await form.locator('[name=date]').fill('2027-03-15');await form.getByRole('button',{name:'Add one-off'}).click();await page.waitForTimeout(500);const session=await db.session.findFirstOrThrow({where:{tourId:tour.id}});assert.equal(session.capacity,tour.capacityPerDeparture);await page.reload();await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.waitForTimeout(500);assert.equal((await db.session.findUnique({where:{id:session.id}})).status,'CANCELLED');});
 await check('Create, edit and delete promo code',async()=>{await page.goto(base+'/admin/promo-codes');const form=page.locator('form').filter({has:page.locator('[name=code]')});const code='CMS'+Date.now();await form.locator('[name=code]').fill(code);await form.locator('[name=value]').fill('10');await form.locator('button[type=submit]').click();await page.waitForTimeout(500);const promo=await db.promoCode.findUniqueOrThrow({where:{code}});await page.goto(base+'/admin/promo-codes?edit='+promo.id);const edit=page.locator('form').filter({has:page.getByRole('button',{name:'Save changes'})});await edit.locator('[name=value]').fill('15');await edit.getByRole('button',{name:'Save changes'}).click();await page.waitForTimeout(500);assert.equal((await db.promoCode.findUnique({where:{id:promo.id}})).value,15);await page.goto(base+'/admin/promo-codes');const row=page.locator('tr').filter({hasText:code});await row.getByRole('button',{name:'Delete',exact:true}).click();await page.waitForTimeout(500);assert.equal(await db.promoCode.count({where:{id:promo.id}}),0);});
 await page.goto(base+'/admin/tours');await page.screenshot({path:out+'/cms-tours.png',fullPage:true});await db.tour.delete({where:{id:tour.id}});
}finally{await writeFile(out+'/cms.json',JSON.stringify(results,null,2));await writeFile(out+'/cms-server.log',serverLog);await browser?.close();server.kill();await db.adminUser.delete({where:{id:admin.id}});await db.$disconnect();}
